services:
  - type: web
    name: roku-streaming-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: roku-streaming-server
          property: port
    domains:
      - roku-streaming-server.onrender.com
    autoDeploy: true
    branch: main
    rootDir: ./server